build:
  image: framgia/laravel-workspace
  commands:
    - sleep 60
    - chmod -R 777 storage/
    - composer install
    - npm install
    - gulp
    - cp .env.testing .env
    - php artisan migrate --database=mysql_test
    - vendor/bin/phpunit
compose:
  database:
    image: mysql
    environment:
      MYSQL_DATABASE: homestead_test
      MYSQL_USER: homestead_test
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
deploy:
  rocketeer_develop:
    image: framgia/drone-plugin-ssh-php:php5
    when:
      branch: develop
    commands:
      - php rocketeer.phar deploy --on=staging --no-interaction
  rocketeer_production:
    image: framgia/drone-plugin-ssh-php:php5
    when:
      branch: master
    commands:
      - php rocketeer.phar deploy --on=production --no-interaction
cache:
  mount:
    - .git
    - vendor
    - node_modules
